//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXPAppManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClockingTransaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClockingTransaction()
        {
            this.Timesheets = new HashSet<Timesheet>();
            this.Timesheets1 = new HashSet<Timesheet>();
        }
    
        public System.Guid UniqueID { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public System.DateTime DateTime { get; set; }
        public string Justification { get; set; }
        public int ClockType { get; set; }
        public System.Guid AppUserID { get; set; }
        public Nullable<System.Guid> TimesheetID { get; set; }
        public Nullable<System.Guid> ClockingLocationID { get; set; }
        public string UserEmailAddress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Timesheet> Timesheets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Timesheet> Timesheets1 { get; set; }
    }
}
