//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXPAppManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClockLogging
    {
        public string ID { get; set; }
        public string AppUserID { get; set; }
        public string LogDetails { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateSent { get; set; }
        public string type { get; set; }
        public string connectionType { get; set; }
    }
}
