//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXPAppManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nop_Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Nop_Customer()
        {
            this.Nop_CustomerAttribute = new HashSet<Nop_CustomerAttribute>();
        }
    
        public int CustomerID { get; set; }
        public System.Guid CustomerGUID { get; set; }
        public string Email { get; set; }
        public string Username { get; set; }
        public string PasswordHash { get; set; }
        public string SaltKey { get; set; }
        public int AffiliateID { get; set; }
        public int BillingAddressID { get; set; }
        public int ShippingAddressID { get; set; }
        public int LastPaymentMethodID { get; set; }
        public string LastAppliedCouponCode { get; set; }
        public string GiftCardCouponCodes { get; set; }
        public string CheckoutAttributes { get; set; }
        public int LanguageID { get; set; }
        public int CurrencyID { get; set; }
        public int TaxDisplayTypeID { get; set; }
        public bool IsTaxExempt { get; set; }
        public bool IsAdmin { get; set; }
        public bool IsGuest { get; set; }
        public bool IsForumModerator { get; set; }
        public int TotalForumPosts { get; set; }
        public string Signature { get; set; }
        public string AdminComment { get; set; }
        public bool Active { get; set; }
        public bool Deleted { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public string TimeZoneID { get; set; }
        public int AvatarID { get; set; }
        public Nullable<int> SITOrganisationID { get; set; }
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nop_CustomerAttribute> Nop_CustomerAttribute { get; set; }
    }
}
