//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXPAppManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nop_Picture
    {
        public int PictureID { get; set; }
        public byte[] PictureBinary { get; set; }
        public string Extension { get; set; }
        public bool IsNew { get; set; }
    }
}
