//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXPAppManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIT_AuthorisationGroups
    {
        public int AuthorisationGroupId { get; set; }
        public Nullable<int> OrganisationId { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> AuthoriseeId { get; set; }
        public int Deleted { get; set; }
    }
}
