//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXPAppManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIT_Organisation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SIT_Organisation()
        {
            this.SIT_Address = new HashSet<SIT_Address>();
        }
    
        public int OrganisationID { get; set; }
        public string Theme { get; set; }
        public string OrganisationName { get; set; }
        public string SageAccount { get; set; }
        public Nullable<int> PriceProfile { get; set; }
        public Nullable<int> DeliveryProfile { get; set; }
        public Nullable<System.Guid> OrganisationGUID { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string OverrideEmail { get; set; }
        public Nullable<bool> Template { get; set; }
        public bool IndividualCostCentres { get; set; }
        public string ReturnUniformName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIT_Address> SIT_Address { get; set; }
    }
}
